language: python
python:
- 2.7
- 3.7
- 3.8
install: pip install tox-travis coveralls
script:
- tox
after_success:
- coverage combine
- coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: MErT2dPZ0SyHgp8ijzP+PTPeNgt1GkDTiz6QStQqo1JWstV1mZIIiouBv/C6E2712wJoIh6y6IBmH8cgx8jaoKDEs8Wj6d9zqoG2WPYOCa7coxFPC8+9Y3HrykK+mcb01T6rUt3tAeZjw/CsO083eNT0hhKswsNy6JbszwiJE58P2HgFPWyqo6v3G3b8VdtXG+tIgI7XwgoAUU6uKfck0mzh98z00KHsSL8t00Y5ecazcZf+TFxtKTZxzHCfkCkNEK0iZFmDFp1sw1a72zBwnLuzgSlAKyLOrILhgv0Zp2EEahLZhJiF8hNYT1htpb3K+O6MIutrwxhVKnbmjaIX5WEcVmFt041zM7qAASMBNh9kAT74DyikkcbNy1EiyA/Jum909el9WuwiadMszobB7b+YekHDJiUYMmT52pVYnM26fuUpXX8mZDmV/WmJq06T1ZxsrysRMZdKbmTPCViQaGulOqbTkCxFlTqgOLKy/eVfwzSoyyk+o8Ibw0Q4YYXwNMmpEokos1vqqEKNlQDtXe+s65M1qXDebMLxtRqpev1Bi0euawxDpjhiPJLr0nydeIREhRyxyYA52dr6B3u2WJwHbQM7Lhxtx5MF+RijbwBFxXzZtd0oAK3RJeynN1x1B797CBGNSVssFG8HdLoWRPRPH3mf5CdhkLzBzIN80/Q=
